stages:
  - test

test:
  image: cypress/browsers:node16.5.0-chrome94-ff93
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run 
    - cy:smoke
    - npm run runOnChrome
