
stages:
  - test

test:

  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run cy:smoke
    # run Cypress tests
    - npm run cy:dashboard