stages:
  - test

test:
  image: cypress/browsers:node16.5.0-chrome94-ff93
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run 
    - "curl -X POST --fail -F token=TOKEN -F ref=REF_NAME https://gitlab.com/api/v4/projects/36082628/trigger/pipeline"
    - npm run runOnChrome
